apiVersion: v1
kind: ReplicationController
metadata:
  name: vertex-rc
spec:
  replicas: 5
  selector:
   app: 
   version: 2.6.2
  template:
    metadata:
     labels:
          app: verteximage9dec22
          version: 2.6.2
    spec: 
      containers: 
        - name: mycgjavapp-container
          image: sandip1994/verteximage9dec22:1
          ports:
          - containerPort: 8080
          
       