apiVersion: v1
kind: Service
metadata:
  name: vertex-scv
  labels: 
   app: verteximage9dec22
spec: 
  type: NodePort
  ports: 
   - port: 8080
     nodePort: 30001
     protocol: TCP
  selector: 
    app: verteximage9dec22    